
MODULE = SerialTest

FORKS= waba superwaba
RUN_FORK= superwaba

MW_CLASS= SerialTest

EXE_CLASS_HEAP_SIZE = 10000000
EXE_OBJ_HEAP_SIZE = 5000000

include ../ReleaseSystem/waba.inc

all: dependencies main warp jar exgen
