#!/bin/bash
javac -classpath ~/jump/jar/jump.jar:~/source/wabajump/classes *.java
~/pilrc/pilrc -R AddrScan.res AddrScan.rcp
ibmjava -classpath ~/jump/jar/jump.jar:.:~/source/wabajump/classes:$CLASSPATH Jump -mw AddrScan
export PILAINC=~/pila
~/pila/pila AddrScan.asm
rm *.bin
rm *.asm
rm *.res
rm *.class
