#!/bin/bash
javac -classpath ~/jump/jar/jump.jar:~/source/wabajump/classes *.java
~/pilrc/pilrc -R CoreTest.res CoreTest.rcp
ibmjava -classpath ~/jump/jar/jump.jar:.:~/source/wabajump/classes:$CLASSPATH Jump -mw CoreTest
export PILAINC=~/pila
~/pila/pila CoreTest.asm
rm -f *.bin
rm -f *.asm
rm -f *.res
rm -f *.class
