WABA_DIR= /home/scytacki/waba/superwaba/vmsrc/classes_java
WEXTRAS_DIR= /home/scytacki/waba/superwaba/wextras/classes

SRC= JGraphics.java TextLine.java \
	Axis.java BarSet.java BarGraph.java \
	Graph2D.java LineGraph.java ScrollLineGraph.java

comp:
	javac -O -d . -classpath "${CLASSPATH}:${WABA_DIR}:${WEXTRAS_DIR}" \
$(SRC)
