/* DO NOT EDIT THIS FILE - it is machine generated */
/* Generated for class waba.io.impl.JDirectImpl */
/* Generated from JDirectImpl.java*/

#ifndef _Included_waba_io_impl_JDirectImpl
#define _Included_waba_io_impl_JDirectImpl
#include <jni.h>
#ifdef __cplusplus
extern "C" {
#endif

/**
	JDirectSerialPort is Waba's SerialPort implementation for Mac OS less than X
	JDirectSerialPort uses JDirect2 for calling MAC OS Toolbox's routines
*/

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    OpenDriver
 * Signature: ([B[S)S
 */

/**
	 @param name			in C: <CODE>ConstStr255Param name</CODE>
	 @param drvrRefNum	in C: <CODE>short *drvrRefNum</CODE>
	 @return				in C: <CODE>OSErr </CODE>
*/

JNIEXPORT jshort JNICALL Java_waba_io_impl_JDirectImpl_OpenDriver
	(JNIEnv *, jclass, jbyteArray, jshortArray);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    CloseDriver
 * Signature: (S)S
 */

/**
	 @param refNum		in C: <CODE>short refNum</CODE>
	 @return				in C: <CODE>OSErr </CODE>
*/

JNIEXPORT jshort JNICALL Java_waba_io_impl_JDirectImpl_CloseDriver
	(JNIEnv *, jclass, jshort);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    KillIO
 * Signature: (S)S
 */

/**
	 @param refNum		in C: <CODE>short refNum</CODE>
	 @return				in C: <CODE>OSErr </CODE>
*/

JNIEXPORT jshort JNICALL Java_waba_io_impl_JDirectImpl_KillIO
	(JNIEnv *, jclass, jshort);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    Control
 * Signature: (SS[B)S
 */

/**
	 @param refNum		in C: <CODE>short refNum</CODE>
	 @param csCode		in C: <CODE>short csCode</CODE>
	 @param csParamPtr	in C: <CODE>const void *csParamPtr</CODE>
	 @return				in C: <CODE>OSErr </CODE>
*/

JNIEXPORT jshort JNICALL Java_waba_io_impl_JDirectImpl_Control
	(JNIEnv *, jclass, jshort, jshort, jbyteArray);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    PBWriteSync
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_waba_io_impl_JDirectImpl_PBWriteSync
	(JNIEnv *, jclass, jint);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    PBReadSync
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_waba_io_impl_JDirectImpl_PBReadSync
	(JNIEnv *, jclass, jint);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    SerReset
 * Signature: (SS)S
 */

/**
	 @param refNum		in C: <CODE>short refNum</CODE>
	 @param serConfig		in C: <CODE>short serConfig</CODE>
	 @return				in C: <CODE>OSErr </CODE>
*/

JNIEXPORT jshort JNICALL Java_waba_io_impl_JDirectImpl_SerReset
	(JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    SerGetBuf
 * Signature: (S[I)S
 */

/**
	 @param refNum		in C: <CODE>short refNum</CODE>
	 @param count			in C: <CODE>long *count</CODE>
	 @return				in C: <CODE>OSErr </CODE>
*/

JNIEXPORT jshort JNICALL Java_waba_io_impl_JDirectImpl_SerGetBuf
	(JNIEnv *, jclass, jshort, jintArray);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    NewPtr
 * Signature: (I)I
 */

/**
	 @param byteCount		in C: <CODE>Size byteCount</CODE>
	 @return				in C: <CODE>Ptr </CODE>
*/

JNIEXPORT jint JNICALL Java_waba_io_impl_JDirectImpl_NewPtr
	(JNIEnv *, jclass, jint);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    NewPtrClear
 * Signature: (I)I
 */

/**
	 @param byteCount		in C: <CODE>Size byteCount</CODE>
	 @return				in C: <CODE>Ptr </CODE>
*/

JNIEXPORT jint JNICALL Java_waba_io_impl_JDirectImpl_NewPtrClear
	(JNIEnv *, jclass, jint);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    DisposePtr
 * Signature: (I)V
 */

/**
	 @param p				in C: <CODE>Ptr p</CODE>
*/

JNIEXPORT void JNICALL Java_waba_io_impl_JDirectImpl_DisposePtr
	(JNIEnv *, jclass, jint);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    GetPtrSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_waba_io_impl_JDirectImpl_GetPtrSize
	(JNIEnv *, jclass, jint);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    GetHandleSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_waba_io_impl_JDirectImpl_GetHandleSize
	(JNIEnv *, jclass, jint);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    InitCRM
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_waba_io_impl_JDirectImpl_InitCRM
	(JNIEnv *, jclass);

/*
 * Class:     waba_io_impl_JDirectImpl
 * Method:    CRMSearch
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_waba_io_impl_JDirectImpl_CRMSearch
	(JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
