#! /bin/bash

if ! [ $workingcopy ]
then echo "********please set \$workingcopy to ccprobe project root*****"
if [ -x ../../XML2LabBook/make-labbook ]; then
echo "I just took a guess and found the needed file"
../../XML2LabBook/make-labbook $1 $2
fi
exit
fi

if [ $1 ]
then labbook=$1
else labbook="labbook.xml"
fi

$workingcopy/XML2LabBook/make-labbook $labbook





