#!/bin/bash
javac -classpath ~/source/wabajump/classes *.java
~/pilrc/pilrc -R wabatest.res wabatest.rcp
ibmjava -classpath ~/jump/jar/jump.jar:.:~/source/wabajump/classes:$CLASSPATH Jump -mw wabatest
export PILAINC=~/pila
~/pila/pila wabatest.asm
rm *.asm
rm *.bin
rm *.class
rm *.res
