#!/bin/bash
javac -classpath /home/scytacki/cvstest/wabajump/classes *.java
~/pilrc/pilrc -R wabatest.res wabatest.rcp
java -classpath ~/jump/jar/jump.jar:.:~/source/wabajump/classes:$CLASSPATH Jump -mw wabatest
export PILAINC=~/pila
~/pila/pila wabatest.asm
rm *.asm
rm *.bin
rm *.class
rm *.res
