#! /bin/bash

if ! [ $workingcopy ]
then echo "********please set \$workingcopy to ccprobe project root*****" ; exit 
fi

if [ $1 ]
then labbook=$1
else labbook="labbook.xml"
fi

$workingcopy/XML2LabBook/make-labbook $labbook





