#! /bin/bash

if [ $workingcopy ]
then echo "using \$workingcopy: " $workingcopy
else echo "********please set \$workingcopy*****" ; exit 
fi

java  -cp $workingcopy/wextra/classes/desktop:$workingcopy/wabasdk/classes:$workingcopy/wgraph/classes/other:$workingcopy/LabBook/classes/other:$workingcopy/CCProbe/classes/other:$workingcopy/XML2LabBook/jars/QTJava.zip:$workingcopy/XML2LabBook/classes/other xml2labbook.XML2LabBook $1 labbook.xml 



