#! /bin/bash

if [ $workingcopy ]
then echo "using \$workingcopy: " $workingcopy
else echo "please set \$workingcopy" ; break
fi

java  -Xint -cp $workingcopy/wextra/classes/desktop:$workingcopy/wabasdk/classes:$workingcopy/wgraph/classes/other:$workingcopy/LabBook/classes/other:$workingcopy/CCProbe/classes/other:$workingcopy/XML2LabBook/jars/QTJava.zip:$workingcopy/XML2LabBook/classes/other xml2labbook.XML2LabBook labbook.xml 



