/*   DO NOT MANUALLY EDIT THIS FILE!  */ //too late!

/* This code was generated by
  UIGen by Andreas Bade
  2000/6/1 ,  16:48:13  */

import waba.ui.* ;

public class DiceRollerUI
{

/* Decleration of user interface controls */
Button cmdRoll = new Button( "Roll the Dice!" ) ;
Label lblNumDice = new Label( "Number of Dice to roll:" ) ;
Edit txtNumDice = new Edit() ;
Button cmdChange = new Button( "Set" ) ;
Label lblAuthor = new Label( "Created by Peter Carroll" ) ;
Label lblURL = new Label( "http://www.se77en.com/kedge" ) ;

private float fHeightDiff=1;
private float fWidthDiff=1;

  public DiceRollerUI()
  {
    layoutControls()  ;
    resetEditFields() ;
  }

  public DiceRollerUI(int newHeight, int newWidth)
  {
    fHeightDiff=(float)newHeight/160;
    fWidthDiff=(float)newWidth/160;
    layoutControls()  ;
    resetEditFields() ;
  }

  /** Sets position and size of all
      user interface controls       **/
  public void layoutControls()
  {
    cmdRoll.setRect( (int)(50*fWidthDiff), (int)(110*fHeightDiff), (int)(60*fWidthDiff), (int)(20*fHeightDiff) );
    lblNumDice.setRect( (int)(0*fWidthDiff), (int)(20*fHeightDiff), (int)(100*fWidthDiff), (int)(20*fHeightDiff) );
    txtNumDice.setRect( (int)(100*fWidthDiff), (int)(17*fHeightDiff), (int)(8*fWidthDiff), (int)(20*fHeightDiff) );
    cmdChange.setRect( (int)(120*fWidthDiff), (int)(23*fHeightDiff), (int)(25*fWidthDiff), (int)(15*fHeightDiff) );
    lblAuthor.setRect( (int)(30*fWidthDiff), (int)(130*fHeightDiff), (int)(120*fWidthDiff), (int)(20*fHeightDiff) );
    lblURL.setRect( (int)(20*fWidthDiff), (int)(140*fHeightDiff), (int)(130*fWidthDiff), (int)(20*fHeightDiff) );
  }
  /** Adds the user interface controls to
    * a container.
    * @param container the container to which the
                       controls is to be added
   **/

  public void addTo( Container container )
  {
    container.add( cmdRoll );
    container.add( lblNumDice );
    container.add( txtNumDice );
    container.add( cmdChange );
    container.add( lblAuthor );
    container.add( lblURL );
  }

  public void resetEditFields()
  {
    txtNumDice.setText( "6" );
  }

  public void removeFrom( Container container )
  {
    container.remove( cmdRoll );
    container.remove( lblNumDice );
    container.remove( txtNumDice );
    container.remove( cmdChange );
    container.remove( lblAuthor );
    container.remove( lblURL );
  }

  public void handleEvent( Event event, IDiceRollerUI receiver )
  {
    if(    event.target == cmdRoll
        && event.type == ControlEvent.PRESSED )
      { receiver.onRoll() ; }

    if(    event.target == cmdChange
        && event.type == ControlEvent.PRESSED )
      { receiver.onNumDiceEdit() ; }

  }


/*
METACODESTART
BTN00050001100006000020
cmdRoll
Roll the Dice!
onRoll
LBL00000000200010000020
lblNumDice
Number of Dice to roll:

EDT00100000170000800020
txtNumDice
6

BTN00120000230002500015
cmdChange
Set
onNumDiceEdit
LBL00030001300012000020
lblAuthor
Created by Peter Carroll

LBL00020001400013000020
lblURL
http://www.se77en.com/kedge

METACODEEND
*/
}