/* DO NOT MANUALLY EDIT THIS FILE!
   Interface code generated by
   UIGen by Andreas Bade
   2000/6/1 ,  16:48:14             */

public interface IDiceRollerUI
{
  public void onRoll() ;
  public void onNumDiceEdit() ;
}
