#!/bin/bash
javac -classpath ~/jump/jar/jump.jar:~/source/wabajump/classes *.java
~/pilrc/pilrc -R ImageSplit.res ImageSplit.rcp
ibmjava -classpath ~/jump/jar/jump.jar:.:~/source/wabajump/classes:$CLASSPATH Jump -mw ImageSplit
export PILAINC=~/pila
~/pila/pila ImageSplit.asm
rm *.asm
rm *.bin
rm *.class
rm *.res
