#!/bin/bash
javac -classpath ~/jump/jar/jump.jar:~/source/wabajump/classes *.java
~/pilrc/pilrc -R Controls.res Controls.rcp
ibmjava -classpath ~/jump/jar/jump.jar:.:~/source/wabajump/classes:$CLASSPATH Jump -mw Controls
export PILAINC=~/pila
~/pila/pila Controls.asm
rm -f *.bin
rm -f *.asm
rm -f *.res
rm -f *.class
