#! /bin/bash

java -cp /Users/stephen/Development/XML2LabBook/../wextra/classes/desktop:/Users/stephen/Development/XML2LabBook/../wabasdk/classes::/Users/stephen/Development/XML2LabBook/../wgraph/classes/other:/Users/stephen/Development/XML2LabBook/../LabBook/classes/other:/Users/stephen/Development/XML2LabBook/../CCProbe/classes/other:jars/QTJava.zip:/Users/stephen/Development/XML2LabBook/classes/other xml2labbook.XML2LabBook labbook.xml 



