#! /bin/bash
#
# workingcopy should be set to ccprobe project root
#

java  -cp $workingcopy/wextra/classes/desktop:$workingcopy/wabasdk/classes:$workingcopy/wgraph/classes/other:$workingcopy/LabBook/classes/other:$workingcopy/ProbeLib/classes/other:$workingcopy/CCProbe/classes/other:$workingcopy/XML2LabBook/jars/QTJava.zip:../jars/bsf.jar:../jars/js.jar:../jars/xalan.jar:../jar/xerces.jar:$workingcopy/XML2LabBook/classes/other xml2labbook.XML2LabBook $1




