#! /bin/bash

# Try to find the directory of this script
# if the script is on the path then we have problems

scriptdir=`dirname $0`


# see if this auto determined variable is correct
[ -f $scriptdir/`basename $0` ] || echo "you shouldn't run this script from your path"

#if [ $workingcopy ]
#then echo "using \$workingcopy: " $workingcopy
#else echo "********please set \$workingcopy*****" ; exit 
#fi
workingcopy=$scriptdir/..

my_classpath=$workingcopy/wextra/classes/desktop:$workingcopy/wabasdk/classes:$workingcopy/wgraph/classes/other:$workingcopy/LabBook/classes/other:$workingcopy/ProbeLib/classes/other:$workingcopy/CCProbe/classes/other:$workingcopy/XML2LabBook/classes/other:$workingcopy/XML2LabBook/jars/QTManager.jar:$workingcopy/XML2LabBook/jars/xalan.jar:$workingcopy/XML2LabBook/jars/crimson.jar

java  -cp $my_classpath  xml2labbook.XML2LabBook $1 $2



